name: Deploy

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: |
        echo "TAG=$(git rev-parse --short "$GITHUB_SHA")-${{ github.run_id }}" >> $GITHUB_ENV

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Build
      run: |
        docker build -t ${{ secrets.CONTAINER_IMAGE }}:${{ env.TAG }} .

    - name: Push
      run: |
        docker push ${{ secrets.CONTAINER_IMAGE }}:${{ env.TAG }}
      
    - name: Deploy
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'app'
        image: ${{ secrets.CONTAINER_IMAGE }}:${{ env.TAG }}
        region: 'europe-west3'

    - name: 'Test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
